import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function game(){const nodes=new Map();const context=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get:(t,p)=>p in t?t[p]:()=>{}});const node=()=>({style:{},getContext:()=>context,textContent:'',hidden:false});const sandbox={document:{querySelector:s=>{if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)},querySelectorAll:()=>[],body:{classList:{add(){},remove(){}}}},localStorage:{getItem:()=>null,setItem(){}},addEventListener(){},requestAnimationFrame(){},setTimeout(){},devicePixelRatio:1,innerWidth:1280,innerHeight:720,Math,console};vm.createContext(sandbox);vm.runInContext(readFileSync(new URL('../game.js',import.meta.url),'utf8'),sandbox);return code=>vm.runInContext(code,sandbox)}
test('world renders and player lands on starting ground',()=>{const run=game();run("mode='play'; for(let i=0;i<120;i++)update(1/60);draw()");assert.equal(run('player.y+player.h'),610);assert.equal(run('player.hp'),6)});
test('double jump and dash grant movement without a third jump',()=>{const run=game();run("mode='play';player.jumps=0;pressed.add('Space');update(.016);pressed.clear()");assert.equal(run('player.jumps'),1);run("pressed.add('Space');update(.016);pressed.clear()");assert.equal(run('player.jumps'),2);run("pressed.add('Space');update(.016);pressed.clear()");assert.equal(run('player.jumps'),2);run("pressed.add('KeyK');update(.016)");assert.ok(run('player.dash>0 && player.inv>0 && player.vx>800'))});
test('sword kills nearby enemy and restores soul',()=>{const run=game();run("mode='play';player.x=685;player.y=562;player.soul=20;enemies[0].hp=1;pressed.add('KeyJ');update(.016)");assert.equal(run('enemies[0].hp'),0);assert.equal(run('player.embers'),12);assert.equal(run('player.soul'),29)});
test('boss activates, attacks, and victory removes arena hazards',()=>{const run=game();run("mode='play';player.x=3800;player.y=562;update(.016)");assert.ok(run('boss.active'));run("boss.timer=0;update(.016)");assert.equal(run('boss.state'),'wind');run("boss.timer=0;update(.016)");assert.equal(run('boss.state'),'charge');run("boss.x=4300;boss.y=610;boss.hp=1;player.x=4240;player.y=540;player.face=1;pressed.add('KeyJ');update(.016)");assert.ok(run('won'));assert.equal(run('boss.active'),false);assert.equal(run('waves.length'),0)});
test('lantern heals and establishes respawn checkpoint',()=>{const run=game();run("mode='play';player.x=3260;player.y=562;player.hp=2;pressed.add('KeyE');update(.016)");assert.equal(run('checkpoint'),3260);assert.equal(run('player.hp'),6);run('player.x=4000;respawn()');assert.equal(run('player.x'),3260)});
